### ISSUE TITLE
Setup the kanban board

### ISSUE THREAD

**Issue by ciraganenicole** [LionRouge1/Space_travelers#25]
- [Project link](https://github.com/LionRouge1/Space_travelers/projects/1)

- We are 2 people

**Comment by dasileker** [comment]
### **Hi @LionRouge1,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
